# Generated by Django 5.2.5 on 2025-09-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('anio', models.PositiveIntegerField()),
            ],
        ),
    ]
